import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Importing the Components
import LayoutContent from "../components/LayoutContent";

// Importing the Context
import { AuthProvider } from "../context/AuthContext"; // Contexto vem antes de ser usado

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Agendetor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-full`}
      >
        <AuthProvider>
          {/* Mova a lógica de autenticação para os componentes */}
          <LayoutContent>{children}</LayoutContent>
        </AuthProvider>
      </body>
    </html>
  );
}
